server:
  port: 8761
spring:
  application:
    name: discovery-ws
eureka:
  client:
    service-url:
      defaultZone: http://172.18.10.38:8761/eureka
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true    